#!/bin/sh
module="cryptocard_mod"
device="cryptocard_mod"
mode="664"

make

sudo /sbin/insmod ./$module.ko || exit 1

sudo rm -f /dev/$device

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

sudo mknod /dev/$device c $major 0

group="staff"
sudo chgrp $group /dev/$device
sudo chmod $mode /dev/$device
